import type { GenreMeta } from "@/types/genre";

// Each entry links to a top-level route at app/<slug>/page.tsx.
// Cover assets live at public/genres/<slug>/cover.* (+ cover-poster.jpg for video covers).
// Add a genre by adding an entry here AND creating that folder.
export const genres: GenreMeta[] = [
  {
    slug: "illustrations",
    title: "Illustrations",
    summary: "A short one-line description of this genre.",
    cover: "/genres/illustrations/cover.png",
    coverWidth: 1427,
    coverHeight: 1606,
    tags: ["Design", "Web"],
    images: [
      {
        src: "/genres/illustrations/islamic-relief.jpeg",
        width: 960,
        height: 1165,
        alt: "Islamic Relief Artwork",
        description: "A short placeholder description of this piece.",
      },
    ],
  },
  {
    slug: "graphic-design",
    title: "Graphic Design",
    summary: "A short one-line description of this genre.",
    cover: "/genres/graphic-design/cover.png",
    coverWidth: 1188,
    coverHeight: 1147,
    tags: ["Design"],
    images: [
      {
        src: "/genres/graphic-design/cover.png",
        width: 1188,
        height: 1147,
        alt: "Graphic design piece",
        description: "A short placeholder description of this piece.",
      },
    ],
  },
  {
    slug: "henna",
    title: "Henna",
    summary: "A short one-line description of this genre.",
    cover: "/genres/henna/cover.png",
    coverWidth: 1448,
    coverHeight: 2835,
    tags: ["Henna"],
    images: [
      {
        src: "/genres/henna/aunty-ji/aunty-ji-1.JPG",
        width: 1093,
        height: 1457,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/aunty-ji/aunty-ji-2.jpg",
        width: 1080,
        height: 1350,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/dazed/dazed-1.jpg",
        width: 1170,
        height: 1462,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-1.jpg",
        width: 1067,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-2.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-3.jpg",
        width: 750,
        height: 422,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-4.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-5.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-6.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-7.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-8.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-9.jpg",
        width: 1170,
        height: 1560,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-10.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-11.jpg",
        width: 1200,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-12.png",
        width: 773,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-13.png",
        width: 868,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
      {
        src: "/genres/henna/levis/levis-14.png",
        width: 1420,
        height: 1600,
        alt: "Henna design piece",
        description: "A short placeholder description of this piece.",
      },
    ],
  },
  {
    slug: "paintings",
    title: "Paintings",
    summary: "A short one-line description of this genre.",
    cover: "/genres/paintings/cover.png",
    coverWidth: 1057,
    coverHeight: 1057,
    tags: ["Paintings"],
  },
  {
    slug: "animations",
    title: "Animations",
    summary: "A short one-line description of this genre.",
    cover: "/genres/animations/cover.webp",
    coverAnimation: "/genres/animations/cover.webp",
    coverWidth: 960,
    coverHeight: 506,
    tags: ["Animation"],
  },
  {
    slug: "residencies",
    title: "Residencies",
    summary: "A short one-line description of this genre.",
    cover: "/genres/residencies/cover.jpg",
    coverWidth: 561,
    coverHeight: 394,
    tags: ["Residencies"],
  },
  {
    slug: "about",
    title: "About",
    summary: "A short one-line description of this genre.",
    cover: "/genres/about/cover-poster.jpg",
    coverVideo: "/genres/about/cover.mp4",
    coverWidth: 480,
    coverHeight: 480,
    tags: ["About"],
  },
];

export function getGenreMeta(slug: string): GenreMeta | undefined {
  return genres.find((genre) => genre.slug === slug);
}
