export type HandImage = {
  src: string;
  width: number;
  height: number;
  // Exactly one of top/bottom anchors the image vertically — top for images
  // in the normal flow, bottom for images that should stay pinned to the
  // end of the page even if content above them changes height.
  top?: number; // percentage down the page
  bottom?: number; // percentage up from the bottom of the page
  left: number; // percentage across the page
  rotate?: number; // degrees, defaults to 0
  scale?: number; // multiplier, defaults to 1
};

// Decorative frame photos for this page only — not part of the shared
// GenreMeta/GalleryImage model since they're specific to this one layout.
// top/left/rotate are hand-tuned approximations of the sketch — nudge these
// directly to reposition any individual hand.
export const hands: HandImage[] = [
  {
    src: "/genres/henna/hands/henna-1.png",
    width: 1344,
    height: 1600,
    top: 2,
    left: 50,
    rotate: 0,
  },
  {
    src: "/genres/henna/hands/henna-2.png",
    width: 1600,
    height: 1517,
    top: 27,
    left: 92,
    rotate: 10,
  },
  {
    src: "/genres/henna/hands/henna-3.png",
    width: 1244,
    height: 1600,
    top: 6,
    left: 6,
    rotate: 7,
    scale: 0.8,
  },
  {
    src: "/genres/henna/hands/henna-4.png",
    width: 1374,
    height: 1600,
    top: 70,
    left: 5,
    rotate: 8,
  },
  {
    src: "/genres/henna/hands/henna-16.png",
    width: 1245,
    height: 977,
    top: 80,
    left: 6,
    rotate: -6,
  },
  {
    src: "/genres/henna/hands/henna-17.png",
    width: 1600,
    height: 1473,
    bottom: 0,
    left: 95,
    rotate: 120,
    scale: 0.9,
  },
  {
    src: "/genres/henna/hands/henna-18.png",
    width: 1360,
    height: 1600,
    bottom: 14,
    left: 6,
    rotate: -5,
  },
  {
    src: "/genres/henna/hands/henna-19.png",
    width: 1413,
    height: 1600,
    bottom: 20,
    left: 30,
    rotate: -40,
  },
  {
    src: "/genres/henna/hands/henna-5.png",
    width: 1403,
    height: 1600,
    top: 60,
    left: 9,
    rotate: -6,
  },
  {
    src: "/genres/henna/hands/henna-6.png",
    width: 1278,
    height: 1600,
    top: 60,
    left: 3,
    rotate: 5,
  },
  {
    src: "/genres/henna/hands/henna-7.png",
    width: 854,
    height: 1600,
    top: 30,
    left: 8,
    rotate: -7,
  },
  {
    src: "/genres/henna/hands/henna-8.png",
    width: 1600,
    height: 1567,
    top: 40,
    left: 10,
    rotate: 6,
  },
  {
    src: "/genres/henna/hands/henna-9.png",
    width: 962,
    height: 1600,
    top: 70,
    left: 97,
    rotate: 25,
    scale: 0.8,
  },
  {
    src: "/genres/henna/hands/henna-10.png",
    width: 917,
    height: 1600,
    top: 35,
    left: 3,
    rotate: -60,
    scale: 0.7,
  },
  {
    src: "/genres/henna/hands/henna-11.png",
    width: 1326,
    height: 1600,
    top: 15,
    left: 8,
    rotate: -80,
  },
  {
    src: "/genres/henna/hands/henna-12.png",
    width: 1600,
    height: 963,
    top: 31,
    left: 93,
    rotate: -5,
  },
  {
    src: "/genres/henna/hands/henna-13.png",
    width: 735,
    height: 1600,
    top: 40,
    left: 95,
    rotate: 6,
  },
  {
    src: "/genres/henna/hands/henna-14.png",
    width: 1084,
    height: 1600,
    top: 40,
    left: 90,
    rotate: -8,
  },
  {
    src: "/genres/henna/hands/henna-15.png",
    width: 1236,
    height: 1600,
    top: 50,
    left: 95,
    rotate: 5,
  },
  {
    src: "/genres/henna/hands/henna-20.png",
    width: 1129,
    height: 1600,
    top: 62,
    left: 93,
    rotate: 7,
  },
  {
    src: "/genres/henna/hands/henna-21.png",
    width: 1211,
    height: 1600,
    top: 75,
    left: 6,
    rotate: -15,
  },
  {
    src: "/genres/henna/hands/henna-22.png",
    width: 1009,
    height: 1600,
    top: 56,
    left: 93,
    rotate: 120,
    scale: 0.8,
  },
  {
    src: "/genres/henna/hands/henna-23.png",
    width: 602,
    height: 429,
    bottom: 17,
    left: 90,
    rotate: 10,
    scale: 1,
  },
  {
    src: "/genres/henna/hands/henna-24.png",
    width: 1089,
    height: 1600,
    bottom: 20,
    left: 93,
    rotate: -6,
  },
  {
    src: "/genres/henna/hands/henna-25.png",
    width: 497,
    height: 1600,
    bottom: 0,
    left: 4,
    rotate: -35,
    scale: 0.5,
  },
  // Bottom-center collage — mixes in with the sketches that cluster near the
  // end of the page, rather than hugging the edges like the rest.

  {
    src: "/genres/henna/hands/henna-26.png",
    width: 552,
    height: 1600,
    top: 7,
    left: 93,
    rotate: 5,
    scale: 0.7,
  },
  {
    src: "/genres/henna/hands/henna-30.png",
    width: 773,
    height: 1600,
    top: 3,
    left: 87,
    rotate: 50,
    scale: 0.85,
  },
  {
    src: "/genres/henna/hands/henna-27.png",
    width: 1506,
    height: 1600,
    bottom: 24,
    left: 3,
    rotate: 6,
    scale: 0.8,
  },
  {
    src: "/genres/henna/hands/henna-28.png",
    width: 1600,
    height: 1303,
    bottom: 4,
    left: 90,
    rotate: 9,
    scale: 0.85,
  },
  {
    src: "/genres/henna/hands/henna-29.png",
    width: 1280,
    height: 1600,
    top: 23,
    left: 5,
    rotate: -7,
    scale: 1,
  },

  {
    src: "/genres/henna/hands/henna-31.png",
    width: 868,
    height: 1600,
    bottom: 20,
    left: 40,
    rotate: -20,
    scale: 0.85,
  },
];
