import type { HandImage } from "./hands";

// Henna design sketches — same freeform decorative treatment as hands.ts,
// interleaved with the hand photos throughout the page rather than
// clustered in one zone. Rendered through the same HandsLayer component.
export const sketches: HandImage[] = [
  {
    src: "/genres/henna/sketches/sketch-1.png",
    width: 1600,
    height: 1535,
    top: 12,
    left: 6,
    rotate: -8,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-2.png",
    width: 1078,
    height: 1600,
    top: 34,
    left: 10,
    rotate: 10,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-3.png",
    width: 1600,
    height: 701,
    top: 58,
    left: 5,
    rotate: -5,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-4.png",
    width: 1600,
    height: 1528,
    top: 70,
    left: 9,
    rotate: 6,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-5.png",
    width: 1600,
    height: 1561,
    top: 14,
    left: 92,
    rotate: 8,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-6.png",
    width: 1600,
    height: 701,
    top: 36,
    left: 96,
    rotate: -10,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-7.png",
    width: 1600,
    height: 1548,
    top: 60,
    left: 90,
    rotate: 5,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-8.png",
    width: 1600,
    height: 1438,
    top: 72,
    left: 94,
    rotate: -6,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-9.png",
    width: 1600,
    height: 1086,
    top: 25,
    left: 20,
    rotate: -12,
    scale: 1.2,
  },
  // Enlarged trio, placed in the open space under the Mother Tongue project
  // near the bottom of the page.
  {
    src: "/genres/henna/sketches/sketch-10.png",
    width: 1600,
    height: 876,
    top: 90,
    left: 25,
    rotate: 12,
    scale: 1.8,
  },
  {
    src: "/genres/henna/sketches/sketch-11.png",
    width: 891,
    height: 1600,
    top: 94,
    left: 50,
    rotate: 8,
    scale: 1.9,
  },
  {
    src: "/genres/henna/sketches/sketch-12.png",
    width: 1600,
    height: 1600,
    top: 90,
    left: 75,
    rotate: 0,
    scale: 1.8,
  },
];
