import type { HandImage } from "./hands";

// Henna design sketches — same freeform decorative treatment as hands.ts,
// interleaved with the hand photos throughout the page rather than
// clustered in one zone. Rendered through the same HandsLayer component.
export const sketches: HandImage[] = [
  {
    src: "/genres/henna/sketches/sketch-1.png",
    width: 1600,
    height: 1535,
    top: 0,
    left: 10,
    rotate: -100,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-2.png",
    width: 1078,
    height: 1600,
    top: 3,
    left: 30,
    rotate: 10,
    scale: 1.2,
  },
  // {
  //   src: "/genres/henna/sketches/sketch-3.png",
  //   width: 1600,
  //   height: 701,
  //   top: 50,
  //   left: 8,
  //   rotate: -105,
  //   scale: 1.8,
  // },
  {
    src: "/genres/henna/sketches/sketch-5.png",
    width: 1600,
    height: 1561,
    top: 20,
    left: 92,
    rotate: 150,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-7.png",
    width: 1600,
    height: 1548,
    top: 11,
    left: 7,
    rotate: -160,
    scale: 1,
  },
  {
    src: "/genres/henna/sketches/sketch-8.png",
    width: 1600,
    height: 1438,
    top: 72,
    left: 94,
    rotate: -6,
    scale: 1.2,
  },
  {
    src: "/genres/henna/sketches/sketch-9.png",
    width: 1600,
    height: 1086,
    top: 3,
    left: 66,
    rotate: 40,
    scale: 1.2,
  },
  // Enlarged trio, placed in the open space under the Mother Tongue project
  // near the bottom of the page.

  {
    src: "/genres/henna/sketches/sketch-10.png",
    width: 1600,
    height: 876,
    top: 105,
    left: 72,
    rotate: 0,
    scale: 3,
  },

  {
    src: "/genres/henna/sketches/sketch-4.png",
    width: 1600,
    height: 1528,
    bottom: 10,
    left: 91,
    rotate: 170,
    scale: 1.4,
  },
  {
    src: "/genres/henna/sketches/sketch-6.png",
    width: 1600,
    height: 701,
    bottom: 10,
    left: 15,
    rotate: -10,
    scale: 2,
  },
  {
    src: "/genres/henna/sketches/sketch-12.png",
    width: 1600,
    height: 1600,
    bottom: 5,
    left: 13,
    rotate: -189,
    scale: 1.8,
  },
  {
    src: "/genres/henna/sketches/sketch-11.png",
    width: 891,
    height: 1600,
    top: 100,
    left: 37,
    rotate: 8,
    scale: 1.9,
  },
];
