import type { HandImage } from "./hands";

// Henna design sketches — same freeform decorative treatment as hands.ts,
// scattered in the gaps between/below the hand photos rather than overlapping
// them. Rendered through the same HandsLayer component.
export const sketches: HandImage[] = [
  {
    src: "/genres/henna/sketches/sketch-1.png",
    width: 1600,
    height: 1535,
    top: 60,
    left: 6,
    rotate: -8,
    scale: 1.05,
  },
  {
    src: "/genres/henna/sketches/sketch-2.png",
    width: 1078,
    height: 1600,
    top: 70,
    left: 10,
    rotate: 10,
    scale: 0.98,
  },
  {
    src: "/genres/henna/sketches/sketch-3.png",
    width: 1600,
    height: 701,
    top: 80,
    left: 5,
    rotate: -5,
    scale: 0.98,
  },
  {
    src: "/genres/henna/sketches/sketch-4.png",
    width: 1600,
    height: 1528,
    top: 90,
    left: 9,
    rotate: 6,
    scale: 0.98,
  },
  {
    src: "/genres/henna/sketches/sketch-5.png",
    width: 1600,
    height: 1561,
    top: 60,
    left: 92,
    rotate: 8,
    scale: 1.05,
  },
  {
    src: "/genres/henna/sketches/sketch-6.png",
    width: 1600,
    height: 701,
    top: 70,
    left: 96,
    rotate: -10,
    scale: 0.98,
  },
  {
    src: "/genres/henna/sketches/sketch-7.png",
    width: 1600,
    height: 1548,
    top: 80,
    left: 90,
    rotate: 5,
    scale: 0.98,
  },
  {
    src: "/genres/henna/sketches/sketch-8.png",
    width: 1600,
    height: 1438,
    top: 90,
    left: 94,
    rotate: -6,
    scale: 0.98,
  },
  {
    src: "/genres/henna/sketches/sketch-9.png",
    width: 1600,
    height: 1086,
    top: 15,
    left: 20,
    rotate: -12,
    scale: 0.77,
  },
  {
    src: "/genres/henna/sketches/sketch-10.png",
    width: 1600,
    height: 876,
    top: 15,
    left: 80,
    rotate: 12,
    scale: 0.77,
  },
  {
    src: "/genres/henna/sketches/sketch-11.png",
    width: 891,
    height: 1600,
    top: 35,
    left: 18,
    rotate: 8,
    scale: 0.77,
  },
  {
    src: "/genres/henna/sketches/sketch-12.png",
    width: 1600,
    height: 1600,
    top: 96,
    left: 50,
    rotate: 0,
    scale: 1.12,
  },
];
